#ifndef TEXTUREMAPOBJECTCONSTANTS_H_INCLUDED
#define TEXTUREMAPOBJECTCONSTANTS_H_INCLUDED

/* Map Textures */
/* MapObject::EMPTY */
unsigned int TEXTURE_MAP_EMPTY_H = 64;
unsigned int TEXTURE_MAP_EMPTY_W = 64;
unsigned int TEXTURE_MAP_EMPTY_X = 365;
unsigned int TEXTURE_MAP_EMPTY_Y = 126;
unsigned int TEXTURE_MAP_EMPTY_COUNT = 1;
unsigned int TEXTURE_MAP_EMPTY_OFFSET_X = 0;
unsigned int TEXTURE_MAP_EMPTY_OFFSET_Y = 0;
/* MapObject::DESTRUCTIBLE_WALL */
unsigned int TEXTURE_MAP_DESTRUCTIBLE_H = 64;
unsigned int TEXTURE_MAP_DESTRUCTIBLE_W = 64;
unsigned int TEXTURE_MAP_DESTRUCTIBLE_X = 429;
unsigned int TEXTURE_MAP_DESTRUCTIBLE_Y = 126;
unsigned int TEXTURE_MAP_DESTRUCTIBLE_COUNT = 1;
unsigned int TEXTURE_MAP_DESTRUCTIBLE_OFFSET_X = 0;
unsigned int TEXTURE_MAP_DESTRUCTIBLE_OFFSET_Y = 0;
/* MapObject::INDESTRUCTIBLE_WALL */
unsigned int TEXTURE_MAP_INDESTRUCTIBLE_H = 64;
unsigned int TEXTURE_MAP_INDESTRUCTIBLE_W = 64;
unsigned int TEXTURE_MAP_INDESTRUCTIBLE_X = 439;
unsigned int TEXTURE_MAP_INDESTRUCTIBLE_Y = 126;
unsigned int TEXTURE_MAP_INDESTRUCTIBLE_COUNT = 1;
unsigned int TEXTURE_MAP_INDESTRUCTIBLE_OFFSET_X = 0;
unsigned int TEXTURE_MAP_INDESTRUCTIBLE_OFFSET_Y = 0;

#endif // TEXTUREMAPOBJECTCONSTANTS_H_INCLUDED
