#ifndef TEXTUREEXPLOSIONCONSTANTS_H_INCLUDED
#define TEXTUREEXPLOSIONCONSTANTS_H_INCLUDED

/* Explosion */
unsigned int TEXTURE_EXPLOSION_H = 100;
unsigned int TEXTURE_EXPLOSION_W = 100;
unsigned int TEXTURE_EXPLOSION_X = 0;
unsigned int TEXTURE_EXPLOSION_Y = 286;
unsigned int TEXTURE_EXPLOSION_COUNT = 74;
unsigned int TEXTURE_EXPLOSION_OFFSET_X = 100;
unsigned int TEXTURE_EXPLOSION_OFFSET_Y = 0;
unsigned int TEXTURE_EXPLOSION_LINE_COUNT = 9;
unsigned int TEXTURE_EXPLOSION_LINE_OFFSET_X = 0;
unsigned int TEXTURE_EXPLOSION_LINE_OFFSET_Y = 100;

#endif // TEXTUREEXPLOSIONCONSTANTS_H_INCLUDED
